# Generated by Django 3.1.7 on 2021-03-22 18:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='exchangeTimezoneName',
            field=models.CharField(default=django.utils.timezone.now, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stock',
            name='market',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
