# Generated by Django 3.1.7 on 2021-05-27 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_inventory'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Inventory',
            new_name='Purchase',
        ),
    ]
