# Generated by Django 3.1.7 on 2021-05-28 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20210527_1842'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activity',
            old_name='price_entered',
            new_name='buying_price',
        ),
        migrations.RenameField(
            model_name='activity',
            old_name='date_activity',
            new_name='date_to_buy',
        ),
        migrations.AddField(
            model_name='activity',
            name='date_to_sell',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='selling_price',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='type_activity',
            field=models.CharField(max_length=10),
        ),
    ]
