# Generated by Django 3.1.7 on 2021-06-24 21:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_remove_news_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='portfolio',
        ),
        migrations.AddField(
            model_name='news',
            name='stock',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.stock'),
        ),
    ]
